runtime: nodejs10
env_variables:
  INSTANCE_CONNECTION_NAME: social-fabric-260013:us-west2:prod
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: social-fabric-260013:us-west2:prod